Use page router instead of app router
It solves the following error:

Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=108 uv=1 armv=8 libc=glibc node=18.17.1 webpack=true